# spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring.datasource.url: jdbc:h2:tcp://localhost:9092/file:./target/camunda-h2-database
server:
  port: 8082
  servlet:
    session:
      cookie:
        name: JSESSIONID2

camunda:
  bpm:
    job-execution:
      deployment-aware: true
    process-engine-name: Service2
    admin-user:
      id: admin
      password: admin
