# spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring.datasource.url: jdbc:h2:tcp://localhost:9092/file:./target/camunda-h2-database;INIT=CREATE SCHEMA IF NOT EXISTS service1\;SET SCHEMA service1\;
server:
  port: 8081
  servlet:
    session:
      cookie:
        name: JSESSIONID1

camunda:
  bpm:
    database:
      schema-name: service1
      table-prefix: service1.
    job-execution:
      deployment-aware: true
    process-engine-name: Service1
    admin-user:
      id: admin
      password: admin
